### ISSUE TITLE
Support for wiki pages

### ISSUE THREAD

**Issue by vpicavet** [ianepperson/pyredminews#12]
Hi,

It would be great to add support for wiki pages access and modification in the API !

First step would be to access current page, then maybe all versions and diffs too.

**Comment by ianepperson** [comment]
Reviewing the spec's and checking out the returned data, it appears that wiki pages have no ID!  Argh!  I'm going to have to add some special-case stuff to either fake the ID for the rest of the logic to function, or special-case stuff for the wiki pages.

Adding the ability to read the pages is pretty strait-forward, however because the parent pages don't really have a unique ID, that data will not come back as a separate object but rather as simply a string.

**Comment by ianepperson** [comment]
I just checked in a change that adds wiki pages access.  You can get a wiki page, edit and save it.  You can get an old version too, but comparing the text is going to be up to the larger app.  I've tried a bunch of different REST syntaxes for creating a new wiki page, but it simply doesn't seem to work - Redmine returns a 404 every time, so that's not working for now.

``` python
server = Redmine('http://my.redmine.server.com')
project = server.project['my_project']
test_page = project.wiki_pages['test']
print test_page.text
# h1. Test
# 
# It's a test!
print test_page.version
# 5
test_page.text += 'h2. Heading\r\n\r\nUpdated page!'
# This will throw a not-authorized error if the latest version isn't 5 (someone edited the page)
test_page.save()

old_test_page = project.wiki_pages['test/3']
print old_test_page.version
# 3
```

Let me know if this works for you.

**Comment by vpicavet** [comment]
That's great, thanks a lot !
